name: orders_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  freezed: ^2.4.7
  injectable: ^2.4.4
  dartz: ^0.10.1
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  fl_chart: ^0.69.2
  intl:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/orders.json
